[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/yahoo/*"
  to = "https://query1.finance.yahoo.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/naver-stock/*"
  to = "https://m.stock.naver.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/naver/*"
  to = "https://api.finance.naver.com/:splat"
  status = 200
  force = true
