name = "pbo-watcher"
main = "worker.js"
compatibility_date = "2026-09-21"

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "SOURCE_CONFIG"
id = "649d43712ad94d038ad832a7b55c863b"